head: 
   favicon: "https://avatars3.githubusercontent.com/u/10670315?v=4&s=50"
   high_res_favicon: "https://avatars0.githubusercontent.com/u/10670315?v=4&s=450"
   apple_touch_icon: "https://avatars0.githubusercontent.com/u/10670315?v=4&s=450"
   keywords: "Metaphors' Blog"

uiux:
   android_chrome_color: "#eeeeee"
   nprogress_color: "#29d"
   nprogress_buffer: 200
   meng: true

background: 
   purecolor: "#eeeeee"

img: 
   avatar: "https://avatars3.githubusercontent.com/u/10670315?v=4&s=100"

card: 
   card_shadow: 1
   card_hoverable: true

many_authors: false

sns_share: 
   weibo: true
   qq: true
   twitter: true
   facebook: true
   googleplus: true
   telegram: false
   linkedin: false
  
comment:
  used: ""
  # disqus config
  disqus_shortname: ""
  disqus_button: true
  disqus_proxy: false
  disqus_proxy_url: ""
  disqus_api_key: ""
  # livere config
  livere_type: 'city'
  livere_data_uid: ''
  # gitment config
  owner: ""
  repo: ""
  client_id: ""
  client_secret: ""
  #valine config
  valine_notify: false
  valine_verify: false
  valine_app_id: ''
  valine_app_key: ''
  valine_placeholder: ""

prism:
  themes: prism-okaidia
  components: 
    - bash 
  plugins: 

mathjax: true

google_analytics: "UA-105616460-1"

lang: "zh-CN"

deploy: ""

custom_css: "" # Use the assets/css/customCss.css

custom_js: "" # Use the assets/js/customJS.js