head: 
   favicon: "https://avatars3.githubusercontent.com/u/10670315?v=4&s=50"
   high_res_favicon: "https://avatars0.githubusercontent.com/u/10670315?v=4&s=450"
   apple_touch_icon: "https://avatars0.githubusercontent.com/u/10670315?v=4&s=450"
   keywords: "Metaphors' Blog"

uiux:
   android_chrome_color: "#eeeeee"
   nprogress_color: "#29d"
   nprogress_buffer: 200
   meng: true

background: 
   purecolor: "#eeeeee"

img: 
   avatar: "https://avatars3.githubusercontent.com/u/10670315?v=4&s=100"

card: 
   card_shadow: 1
   card_hoverable: true

many_authors: false

sns_share: 
   weibo: true
   qq: true
   twitter: true
   facebook: true
   googleplus: true
   telegram: false
   linkedin: false
  
comment:
  used: "livere"
  # disqus config
  disqus_shortname: "metaphors-disqus"
  disqus_button: true
  disqus_proxy: false
  disqus_proxy_url: ""
  disqus_api_key: ""
  # livere config
  livere_type: 'city'
  livere_data_uid: 'MTAyMC8zMDU4My83MTM4'
  # gitment config
  owner: "metaphors"
  repo: "metaphors.github.io"
  client_id: "45e1bc8087e4b783982e"
  client_secret: "878fc8f25951b648c38ef69c23eaa5c154e9f92f"
  #valine config
  valine_notify: false
  valine_verify: false
  valine_app_id: '4K2jPOCa6X9xC15hpslanl03-gzGzoHsz'
  valine_app_key: '2s19HFoS0TTytOej70og9heV'
  valine_placeholder: "写评论"

prism:
  themes: prism-okaidia
  components: 
    - bash 
  plugins: 

mathjax: true

google_analytics: "UA-105616460-1"

lang: "zh-CN"

deploy: ""

custom_css: "" # Use the assets/css/customCss.css

custom_js: "" # Use the assets/js/customJS.js